{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.security",
    "module": "spring-security-test",
    "version": "6.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "6.3.5"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-web",
          "version": {
            "requires": "6.3.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.15"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "6.1.15"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-test-6.3.5.jar",
          "url": "spring-security-test-6.3.5.jar",
          "size": 132216,
          "sha512": "e381d485244e0da30ddbc041d8734e86d5c248818e6d82b4ec50eab272fd85abf5a7e942ccf19d13cb5a49909acebcbe740c5c74216af8a8ca5bb36aaca860eb",
          "sha256": "85cf63ad67866c357be423df5583181064962d1ad49280b7bb533b004ae8dc18",
          "sha1": "25f750d5502cb5b9fc236c7a6b7ae0fa2e1de0c0",
          "md5": "ee83bf83d1e64f0ec4a0894cdf9680bc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "6.3.5"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-web",
          "version": {
            "requires": "6.3.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.15"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "6.1.15"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-test-6.3.5.jar",
          "url": "spring-security-test-6.3.5.jar",
          "size": 132216,
          "sha512": "e381d485244e0da30ddbc041d8734e86d5c248818e6d82b4ec50eab272fd85abf5a7e942ccf19d13cb5a49909acebcbe740c5c74216af8a8ca5bb36aaca860eb",
          "sha256": "85cf63ad67866c357be423df5583181064962d1ad49280b7bb533b004ae8dc18",
          "sha1": "25f750d5502cb5b9fc236c7a6b7ae0fa2e1de0c0",
          "md5": "ee83bf83d1e64f0ec4a0894cdf9680bc"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-test-6.3.5-javadoc.jar",
          "url": "spring-security-test-6.3.5-javadoc.jar",
          "size": 232765,
          "sha512": "ad6f83583667958915c7480a602dce2e377fb8e2fd25ba527b35299aad44400fcf6013880f30196cdf3f24fa14254ab063ffe684d827e29b4ff67915d4d09e0a",
          "sha256": "eeec684205bc72bfccf11a95e8862686f452f9ae6587ad7a221c2e4aa6ea6700",
          "sha1": "36fa9821d8e82c84e3ea5bd424b108e73a21f3b4",
          "md5": "c23bdd833456fb4f7def765c82c7c2bc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-test-6.3.5-sources.jar",
          "url": "spring-security-test-6.3.5-sources.jar",
          "size": 56481,
          "sha512": "4ae360ed8d5dfa03ea1c92bdffddb2a81261d9d90dcd3c4e49aa9abc7ef8fd2a6c413e5198082cbe5dc57d4b5c9ec3dd3051c2594f6540fe56277a5e14a0f2e6",
          "sha256": "0e4f3f31d3750aee40bd427484b5a14fe1a73164d6f340981e8cec516d3dd1c3",
          "sha1": "51f86497cb91451800e84b40a05801f369c1e979",
          "md5": "d6d992d015af6909ca998553401db942"
        }
      ]
    }
  ]
}
