{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.security",
    "module": "spring-security-config",
    "version": "6.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "6.3.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.1.15"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.15"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.1.15"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.15"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-config-6.3.5.jar",
          "url": "spring-security-config-6.3.5.jar",
          "size": 1909565,
          "sha512": "25d535563ecf64dc99113d021a01af42e0159a1de5a40a39774f6512653d74ac70204e47356453864a4223c45e50c76bc30ee6eb19d755548ffef52b1488b0c9",
          "sha256": "9df38f9f76aed283afbbc8a20ee3520ec4efecb81484f4650a5fbd30d191126c",
          "sha1": "a756536086758df1b7bbef3ffd35161e5fe53c40",
          "md5": "828eb493c7b61998ad04db99b8f2206b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "6.3.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.1.15"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.15"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.1.15"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.15"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-config-6.3.5.jar",
          "url": "spring-security-config-6.3.5.jar",
          "size": 1909565,
          "sha512": "25d535563ecf64dc99113d021a01af42e0159a1de5a40a39774f6512653d74ac70204e47356453864a4223c45e50c76bc30ee6eb19d755548ffef52b1488b0c9",
          "sha256": "9df38f9f76aed283afbbc8a20ee3520ec4efecb81484f4650a5fbd30d191126c",
          "sha1": "a756536086758df1b7bbef3ffd35161e5fe53c40",
          "md5": "828eb493c7b61998ad04db99b8f2206b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-config-6.3.5-javadoc.jar",
          "url": "spring-security-config-6.3.5-javadoc.jar",
          "size": 1124717,
          "sha512": "b3880cbdce6cfd8064bdadc03712faaae31b0d5cd9fe02d8a7b9e9253ab0c4b825b5c043a65b3ef6a0ba0a94fe94b838f4f00d5d74e2bb35c7f7118d86229e14",
          "sha256": "9394d3a5252609457b83ebca65b2d51414270b5447dbdebd6d04579e9d0adcd7",
          "sha1": "620495f0d81fabe5d2a9004e51bb728bc4d28547",
          "md5": "c2cb6470f5ade08f4aff6e459ea3921f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-config-6.3.5-sources.jar",
          "url": "spring-security-config-6.3.5-sources.jar",
          "size": 1310780,
          "sha512": "b16d3b176845dcbb24b9aff89a599040dadc83506d390a983012094eb091ad61e4fad078b67e3f532f6c1d04194b1d8f9358470f17cc341736b8a766116dc7bb",
          "sha256": "ff064396d3e1573347785cbccb313c415d768aeeb68d2e7b3bbd687d91e99a15",
          "sha1": "649ef2f340d287ef58c7b9b3e2e3940f74cee96b",
          "md5": "a46fdc7e852451712ba816537884ac65"
        },
        {
          "name": "spring-security-config-6.3.5-sources.jar",
          "url": "spring-security-config-6.3.5-sources.jar",
          "size": 1310780,
          "sha512": "b16d3b176845dcbb24b9aff89a599040dadc83506d390a983012094eb091ad61e4fad078b67e3f532f6c1d04194b1d8f9358470f17cc341736b8a766116dc7bb",
          "sha256": "ff064396d3e1573347785cbccb313c415d768aeeb68d2e7b3bbd687d91e99a15",
          "sha1": "649ef2f340d287ef58c7b9b3e2e3940f74cee96b",
          "md5": "a46fdc7e852451712ba816537884ac65"
        }
      ]
    }
  ]
}
