{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.security",
    "module": "spring-security-web",
    "version": "6.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "6.3.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.15"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.1.15"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.15"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.1.15"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "6.1.15"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.1.15"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-web-6.3.5.jar",
          "url": "spring-security-web-6.3.5.jar",
          "size": 820642,
          "sha512": "b2e3d1857a6e861dd86b9c1ca7b186c8978d8ae982e4c93403e3c8c63ddba59c5ec5fe806d6f78e7bff648458b0a168f6264d2715185c8f9218865123461151c",
          "sha256": "30cc2439dc4e0902effc0d12552e7555131c6275ffc17a5eecc0c5aa2a173040",
          "sha1": "64f47cf0f0665d5cf60e88723102a0fca5a7f2ce",
          "md5": "c50d54297ea2aa3d793c7b9922ffc384"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "6.3.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.15"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.1.15"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.15"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.1.15"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "6.1.15"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.1.15"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-web-6.3.5.jar",
          "url": "spring-security-web-6.3.5.jar",
          "size": 820642,
          "sha512": "b2e3d1857a6e861dd86b9c1ca7b186c8978d8ae982e4c93403e3c8c63ddba59c5ec5fe806d6f78e7bff648458b0a168f6264d2715185c8f9218865123461151c",
          "sha256": "30cc2439dc4e0902effc0d12552e7555131c6275ffc17a5eecc0c5aa2a173040",
          "sha1": "64f47cf0f0665d5cf60e88723102a0fca5a7f2ce",
          "md5": "c50d54297ea2aa3d793c7b9922ffc384"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-web-6.3.5-javadoc.jar",
          "url": "spring-security-web-6.3.5-javadoc.jar",
          "size": 1868424,
          "sha512": "f3e7ed598546847d5c3be3c4fe36d9f078aa30c28584d99618d76b45f6dfdd75dd9e9c799e1b68e442f97a317a6717062f25dcb223c34504d9f8ca85bd392dc5",
          "sha256": "dee9abe3e1bf92d3adb267428c60edf9083c9dad60c3abbe4d7a8de2776e7b73",
          "sha1": "9c2c2d079d36e16386bb021d3e83346a6ff6a58b",
          "md5": "5223ebbfd0611bca6789fc69f1ff4aea"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-web-6.3.5-sources.jar",
          "url": "spring-security-web-6.3.5-sources.jar",
          "size": 673354,
          "sha512": "49835d35db1437b143f683a44f197a11478d0c6c8a2e5c8346ec1d83ad7643193a5449802a6d4c024af8e41ddff0ef6ab6274680a512ea2c1077423f70a25350",
          "sha256": "b7cfc2aa4733d7555d1067cf40848a0b7006989651c4b909e492ec017d503707",
          "sha1": "5a08ad53f474f522038834682c98c3743cc5f0a5",
          "md5": "eac1c8c9f1a9144157587687a72dc8b1"
        }
      ]
    }
  ]
}
